# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-12 07:51
from __future__ import unicode_literals

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaviconPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_favicon_faviconpluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('color', colorfield.fields.ColorField(default='#000', max_length=18)),
                ('icon', filer.fields.image.FilerImageField(help_text='Select an image with', on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL, verbose_name='favicon')),
            ],
            options={
                'verbose_name': 'FaviconPluginModel',
                'verbose_name_plural': 'FaviconPluginModels',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
